spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/linker-shiro?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password: admin
#    database: 0
#    jedis:
#      pool:
#        max-active: 100
#        max-idle: 10
#        min-idle: 3
mybatis:
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.xlccc.entity
server:
  port: 8080

